// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlBfXW-LSxv9CSveIK0rnDHsTeQX8R56Y',
    appId: '1:944868688437:web:5dab4b18bd7d414cd0277c',
    messagingSenderId: '944868688437',
    projectId: 'book-app-184ac',
    authDomain: 'book-app-184ac.firebaseapp.com',
    storageBucket: 'book-app-184ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQxsMOmswirAm8Zst7WGM1M4Kk0j1_3Y',
    appId: '1:944868688437:android:2071ed56274e0822d0277c',
    messagingSenderId: '944868688437',
    projectId: 'book-app-184ac',
    storageBucket: 'book-app-184ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7kVl4ulju1C46sjjw41h5VFMmkzw5iI',
    appId: '1:944868688437:ios:41b123332f6d87dbd0277c',
    messagingSenderId: '944868688437',
    projectId: 'book-app-184ac',
    storageBucket: 'book-app-184ac.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo7kVl4ulju1C46sjjw41h5VFMmkzw5iI',
    appId: '1:944868688437:ios:fb24911c198e186cd0277c',
    messagingSenderId: '944868688437',
    projectId: 'book-app-184ac',
    storageBucket: 'book-app-184ac.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp.RunnerTests',
  );
}
